version: "3.3"
services:
  blog.eana.ro-html:
    image: 395500896865.dkr.ecr.eu-west-1.amazonaws.com/wordpress-snuffleupagus:5.8.1-php7.4-apache
    container_name: blog.eana.ro-html
    restart: always
    ports:
      - 172.17.0.1:8050:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - blog.eana.ro-mysql
    networks:
      - blog.eana.ro-network
  blog.eana.ro-mysql:
    image: mariadb:10.7.1
    container_name: blog.eana.ro-mysql
    restart: always
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/export:/data
    networks:
      - blog.eana.ro-network
networks:
  blog.eana.ro-network:
      driver: bridge
